# Generated by Django 3.2.8 on 2021-10-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.TextField(),
        ),
    ]
